name: 'WeBelieve '
favicon: null
layout_spectrum: 0.8917727873194963
typography_spectrum: 0.7512494623661041
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.02972450666129589
  lightness: 0.13259357144124806
  saturation: 0.4908266912680119
  rhythmicContrast: 0.4166633535642177
purpose: []
