name: 'WeBelieve '
favicon: null
layout_spectrum: 0.8917727873194963
typography_spectrum: 0.7512494623661041
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fef3fb'
    - '#bb000d'
    - '#3c5c65'
    - '#ff6943'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.4908266912680119
  rhythmicContrast: 0.5
purpose: []
